name: Lint Code
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install modules
        run: yarn
      - name: Run Test
        run: yarn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
