name: ESLint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Add dependencies for eslint
      # $GITHUB_WORKSPACE is the path to your repository
      run: echo "::set-env name=NODE_PATH::$GITHUB_WORKSPACE/node_modules"
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
